#!/usr/bin/bash

secretWord=$(shuf -n 1 ./words)
guessUsed=0
guessWord=""
display=""

echo $secretWord
wordCount=$(($(echo $secretWord | wc -c)-1))
echo $wordCount

function printHangman() {
	case $guessUsed in
        0)
            echo "  +---+"
            echo "  |   |"
            echo "      |"
            echo "      |"
            echo "      |"
            echo "      |"
            echo "========="
            ;;
        1)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo "      |"
            echo "      |"
            echo "      |"
            echo "========="
            ;;
        2)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo "  |   |"
            echo "      |"
            echo "      |"
            echo "========="
            ;;
        3)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo " /|   |"
            echo "      |"
            echo "      |"
            echo "========="
            ;;
        4)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo " /|\  |"
            echo "      |"
            echo "      |"
            echo "========="
            ;;
        5)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo " /|\  |"
            echo " /    |"
            echo "      |"
            echo "========="
            ;;
        6)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo " /|\  |"
            echo " / \  |"
            echo "      |"
            echo "========="
            ;;
    esac
}

function blank(){
	display=""
	for ((i=0;i<$wordCount;i++)){
		display="${display}_"
	}
}

checkGuess(){
	found=0
	newDisplay=""
	for ((i=1;i<=$wordCount;i++)){
		currentChar="$(echo $secretWord | cut -c $i)"
		oldChar="$(echo $display | cut -c $i)"

		if [ "$currentChar" == "$guessWord" ]
		then
			newDisplay="${newDisplay}$guessWord"
			found=1
		else
			newDisplay="${newDisplay}$oldChar"
		fi	
	}
	
	display="$newDisplay"	

	if [[ found -eq 0 ]] 
	then
		guessUsed=$((guessUsed+1))
	
	fi
}


showStats(){
	echo Word: $display
	echo Wrong guesses used: $guessUsed
}

blank

until [[ $guessUsed -eq 6 ]]
do
        echo =================================
	echo           Hangman Game
	echo =================================

	printHangman

	showStats

	read -p "Enter one alphabet: " guessWord
	checkGuess
done 
