#!/usr/bin/bash

secretWord=$(shuf -n 1 ./words)
found=0
guessUsed=0

blank=""
guessWord="a"
newDisplay=""

echo $secretWord
wordCount=$(($(echo $secretWord | wc -c)-1))
echo $wordCount
function printHangman() {
	case $guessUsed in
        0)
            echo "  +---+"
            echo "  |   |"
            echo "      |"
            echo "      |"
            echo "      |"
            echo "      |"
            echo "========="
            ;;
        1)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo "      |"
            echo "      |"
            echo "      |"
            echo "========="
            ;;
        2)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo "  |   |"
            echo "      |"
            echo "      |"
            echo "========="
            ;;
        3)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo " /|   |"
            echo "      |"
            echo "      |"
            echo "========="
            ;;
        4)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo " /|\  |"
            echo "      |"
            echo "      |"
            echo "========="
            ;;
        5)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo " /|\  |"
            echo " /    |"
            echo "      |"
            echo "========="
            ;;
        6)
            echo "  +---+"
            echo "  |   |"
            echo "  O   |"
            echo " /|\  |"
            echo " / \  |"
            echo "      |"
            echo "========="
            ;;
    esac
}

function blank(){
	for ((i=0;i<$wordCount;i++)){
		blank="${blank}_ "
	}
}

checkGuess(){
	found=0
	for ((i=1;i<=$wordCount;i++)){
		currentChar="$(echo $secretWord | cut -c $i)"
		oldChar="$(echo $blank | cut -c $i)"

		if $currentChar == $guessWord
		then
			newDisplay="${newDisplay}$guessWord"
			found=1
		else
			newDisplay="${newDisplay}$oldChar"
			found=0
		fi	
	}
	
	if $found -eq 0
	then
		guessUsed=$((guessUsed+1))
	
	fi
	echo guess Used = $guessUsed
}


